### PR TITLE
Building on Mac

### PR DESCRIPTION
**Pull request by doumdi**

### CODE REVIEW

**Comment by philippewarren** [comment]
Might be a good idea to add `macos-10.15` and/or `macos-11` to CI?

**Comment by mamaheux** [comment]
This is a good idea, but the Python tests doesn't work et on macos!

**Review by doumdi — COMMENTED** [review]
Python test do not work yet.

**Comment by doumdi** [comment]
> Might be a good idea to add `macos-10.15` and/or `macos-11` to CI?

Yes but current webrtc version does not compile on macos-11...

**Review by mamaheux — APPROVED** [review]

**Pull request merged**
